#!/bin/sh

if [ -z "$1" ] ; then 
   echo Current version must be specified.
   exit
fi

if [ -z "$2" ] ; then 
   echo New version must be specified.
   exit
fi

CV=$1
echo Current version is $CV

echo New version is $2
SEDCMD="s/<version>$CV<\/version><!--\(.*\)\.version-->/<version>$2<\/version><!--\1.version-->/"
SEDCMDCV="s/$CV/$1/"

find -L . -name 'pom.xml' | xargs sed -i $SEDCMD
#sed -i $SEDCMDCV lojix/lojix/current_version
