#!/bin/sh

if [ -z "$1" ] ; then 
   echo Current version must be specified.
   exit
fi

if [ -z "$2" ] ; then 
   echo New version must be specified.
   exit
fi

CV=$1
echo Current version is $CV
echo New version is $2

SEDCMD="s/<\(.*\)version>$CV<\/\(.*\)version><!--\(.*\)\.version-->/<\1version>$2<\/\2version><!--\3.version-->/"
find -L . -name 'pom.xml' | xargs sed -i $SEDCMD

CVBASE=`cat lojix/base/current_version`
CVLOJIX=`cat lojix/lojix/current_version`
CVDEBUGGER=`cat lojix/debugger/current_version`
CVMAVEN2_PLUGINS=`cat maven2_plugins/current_version`
CVJUNIT_TOOLKIT=`cat junit_toolkit/current_version`
CVJENERATOR=`cat jenerator/current_version`

SEDCMDBASE="s/$CVBASE/$2/"
sed -i $SEDCMDBASE lojix/base/current_version

SEDCMDLOJIX="s/$CVLOJIX/$2/"
sed -i $SEDCMDLOJIX lojix/lojix/current_version

SEDCMDDEBUGGER="s/$CVDEBUGGER/$2/"
sed -i $SEDCMDDEBUGGER lojix/debugger/current_version

SEDCMDMAVEN2_PLUGINS="s/$CVMAVEN2_PLUGINS/$2/"
sed -i $SEDCMDMAVEN2_PLUGINS maven2_plugins/current_version

SEDCMDJUNIT_TOOLKIT="s/$CVJUNIT_TOOLKIT/$2/"
sed -i $SEDCMDJUNIT_TOOLKIT junit_toolkit/current_version

SEDCMDJENERATOR="s/$CVJENERATOR/$2/"
sed -i $SEDCMDJENERATOR jenerator/current_version
