#!/bin/sh

if [ -z "$1" ] ; then 
   echo Current version must be specified.
   exit
fi

if [ -z "$2" ] ; then 
   echo New version must be specified.
   exit
fi

CV=$1
echo Current version is $CV

echo New version is $2
SEDCMD="s/<version>$CV<\/version><!--\(.*\)\.version-->/<version>$2<\/version><!--\1.version-->/"
find -L . -name 'pom.xml' | xargs sed -i $SEDCMD

CVBASE=`cat lojix/base/current_version`
CVLOJIX=`cat lojix/lojix/current_version`
CVDEBUGGER=`cat lojix/debugger/current_version`
CVMAVEN2_PLUGINS=`cat maven2_plugins/current_version`
CVJUNIT_TOOLKIT=`cat junit_toolkit/current_version`
CVJENERATOR=`cat jenerator/current_version`

SEDCMDBASE="s/$CVBASE/$1/"
sed -i $SEDCMDBASE lojix/base/current_version

SEDCMDLOJIX="s/$CVLOJIX/$1/"
sed -i $SEDCMDLOJIX lojix/lojix/current_version

SEDCMDDEBUGGER="s/$CVDEBUGGER/$1/"
sed -i $SEDCMDDEBUGGER lojix/debugger/current_version

SEDCMDMAVEN2_PLUGINS="s/$CVMAVEN2_PLUGINS/$1/"
sed -i $SEDCMDMAVEN2_PLUGINS maven2_plugins/current_version

SEDCMDJUNIT_TOOLKIT="s/$CVJUNIT_TOOLKIT/$1/"
sed -i $SEDCMDJUNIT_TOOLKIT junit_toolkit/current_version

SEDCMDJENERATOR="s/$CVJENERATOR/$1/"
sed -i $SEDCMDJENERATOR jenerator/current_version
