#!/bin/bash

if [ -z "$1" ] ; then 
   echo Commit message must be specified.
   exit
fi

var1=$1

git add .
git commit -m "$1"

#echo for i in `cat modules`; do pushd $i; git add .; git commit -m '$1'; popd; done
