#!/bin/sh

if [ -z "$1" ] ; then 
   echo Commit message must be specified.
   exit
fi

echo git add .
echo git commit -m '$1'

echo for i in `cat modules`; do pushd $i; git add .; git commit -m '$1'; popd; done
